apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-changer-webhook-deployment
  namespace: name-changer
  labels:
    app: name-changer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-changer
  template:
    metadata:
      labels:
        app: name-changer
    spec:
      containers:
        - name: name-changer
          image: pkbhowmick/mutation-webhook:0.1.0
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: name-changer-webhook-certs
