apiVersion: v1
kind: Service
metadata:
  name: name-injector-webhook-svc
  namespace: name-injector
  labels:
    app: name-injector
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: name-injector
