apiVersion: v1
kind: Service
metadata:
  name: name-changer-webhook-svc
  namespace: name-changer
  labels:
    app: name-changer
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app: name-changer
