apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: name-injector-webhook-cfg
  labels:
    app: name-injector
webhooks:
  - name: name-injector.pkbhowmick.me
    clientConfig:
      service:
        name: name-injector-webhook-svc
        namespace: name-injector
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["stable.example.com/v1alpha1"]
        resources: ["kubeapis"]
