apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: name-changer-webhook-cfg
  labels:
    app: name-chnager
webhooks:
  - name: name-changer.pkbhowmick.me
    clientConfig:
      service:
        name: name-changer-webhook-svc
        namespace: name-changer
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: [""]
        apiVersions: ["stable.example.com/v1alpha1"]
        resources: ["kubeapis"]
    namespaceSelector:
      matchLabels:
        name-changer: enabled
